### ISSUE TITLE
insecure script and HTML style rendering problem

### ISSUE THREAD

**Issue by MakerTobey** [DocuBricks/docubricksViewer#13]
Currently, there are a number of smaller documentation viewing issues:
When loading the page, there is a safety related security issue – Error: This page loads scripts from unauthenticated sources, when creating an exception, the documentation style is still not rendered properly and the parts, bill of material, and author links overlap (see screenshot). Persists in multiple browsers.

![viewer_bugs](https://user-images.githubusercontent.com/14097042/32399607-34f782f8-c0ef-11e7-96a2-f4d103e8aa73.png)

**Comment by MakerTobey** [comment]
Done! Works well for DocuBricks.org (for which the security documents were made). On DocuBricks.com, an exception has to be accepted.

**Comment by kasbah** [comment]
The certificates should be valid for both domains. Can you show me where an exception needs to be made?
